using Azure.Core;
using System.Net.Http.Headers;

namespace Anthropic.Foundry;

/// <summary>
/// Provides access to the azure foundry api though the usage of the environmental authentication generated by the <see cref="IAnthropicFoundryCredentials.FromEnv"/> method.
/// </summary>
public class AnthropicFoundryIdentityTokenCredentials : IAnthropicFoundryCredentials
{
    private readonly TokenCredential _tokenCredential;
    private readonly object _tokenLock = new object();
    private AccessToken? _cachedAccessToken;
    private DateTimeOffset _tokenExpiresOn;
    private readonly string[] _scopes = ["https://ai.azure.com/.default"];
    private readonly TimeSpan _tokenCachingTime;

    public string ResourceName { get; }

    /// <summary>
    /// Creates a new instance of the <see cref="AnthropicFoundryIdentityTokenCredentials"/>.
    /// </summary>
    /// <param name="tokenCredential">The credential provider. Use any specialization of <see cref="TokenCredential"/> to get your access token in supported environments.</param>
    /// <param name="resourceName">The service resource subdomain name to use in the anthropic azure endpoint</param>
    /// <param name="scopes">The scopes to use when requesting the token. If null, defaults to "https://ai.azure.com/.default"</param>
    /// <param name="tokenCachingTime">The time to cache the token before requesting a new one. Set for TimeSpan.Zero for no caching. If null, defaults to 5 minutes.</param>
    public AnthropicFoundryIdentityTokenCredentials(TokenCredential tokenCredential, string resourceName, string[]? scopes = null, TimeSpan? tokenCachingTime = null)
    {
        ResourceName = resourceName ?? throw new ArgumentNullException(nameof(resourceName));
        _tokenCredential = tokenCredential ?? throw new ArgumentNullException(nameof(tokenCredential));
        _scopes = scopes ?? _scopes;

        if (tokenCachingTime.HasValue && tokenCachingTime.Value < TimeSpan.Zero)
        {
            throw new ArgumentOutOfRangeException(nameof(tokenCachingTime), "Token caching time must be 0 or greater.");
        }

        _tokenCachingTime = tokenCachingTime ?? TimeSpan.FromMinutes(5);
    }

    public void Apply(HttpRequestMessage requestMessage)
    {
        requestMessage.Headers.Authorization = new AuthenticationHeaderValue(
            "bearer",
            GetAccessToken().Token
        );
    }

    private AccessToken GetAccessToken()
    {
        if (_cachedAccessToken is null || _tokenExpiresOn <= DateTimeOffset.Now)
        {
            lock (this._tokenLock)
            {
                // This will also get the first or refresh the token which is the responsibility of the underlying TokenCredential.GetToken implementation
                this._cachedAccessToken = this._tokenCredential.GetToken(new TokenRequestContext(this._scopes), CancellationToken.None);

                this._tokenExpiresOn = DateTimeOffset.Now.Add(_tokenCachingTime);
            }
        }

        return this._cachedAccessToken.Value;
    }
}
