using Azure.Core;
using System.Net.Http.Headers;

namespace Anthropic.Foundry;

/// <summary>
/// Provides access to the azure foundry api though the usage of the environmental authentication generated by the <see cref="IAnthropicFoundryCredentials.FromEnv"/> method.
/// </summary>
public class AnthropicFoundryIdentityTokenCredentials : IAnthropicFoundryCredentials
{
    private readonly TokenCredential _tokenCredential;
    private readonly object _tokenLock = new object();
    private AccessToken? _cachedAccessToken;
    private readonly string[] _scopes = ["https://ai.azure.com/.default"];

    public string ResourceName { get; }

    /// <summary>
    /// Creates a new instance of the <see cref="AnthropicFoundryIdentityTokenCredentials"/>.
    /// </summary>
    /// <param name="tokenCredential">The credential provider. Use any specialization of <see cref="TokenCredential"/> to get your access token in supported environments.</param>
    /// <param name="resourceName">The service resource subdomain name to use in the anthropic azure endpoint</param>
    /// <param name="scopes">The scopes to use when requesting the token. If null, defaults to "https://ai.azure.com/.default"</param>
    public AnthropicFoundryIdentityTokenCredentials(TokenCredential tokenCredential, string resourceName, string[]? scopes = null)
    {
        ResourceName = resourceName ?? throw new ArgumentNullException(nameof(resourceName));
        _tokenCredential = tokenCredential ?? throw new ArgumentNullException(nameof(tokenCredential));
        _scopes = scopes ?? _scopes;
    }

    /// <summary>
    /// Creates a new instance of the <see cref="AnthropicFoundryIdentityTokenCredentials"/> class.
    /// </summary>
    /// <param name="apiKey">The access token generated by the <see cref="IAnthropicFoundryCredentials.FromEnv"/> method.</param>
    /// <param name="resourceName">The resource name as part of the base url for the api.</param>
    [Obsolete("This constructor is deprecated. Please use the constructor that takes a TokenCredential instead.")]
    public AnthropicFoundryIdentityTokenCredentials(AccessToken apiKey, string resourceName) : this(DelegatedTokenCredential.Create((_, _) => apiKey), resourceName)
    {
        if (apiKey.Equals(default) || string.IsNullOrWhiteSpace(apiKey.Token) || apiKey.ExpiresOn <= DateTimeOffset.Now)
        {
            throw new ArgumentNullException(
                nameof(apiKey),
                "Invalid/Empty or already expired api key struct is not valid"
            );
        }
    }

    public void Apply(HttpRequestMessage requestMessage)
    {
        lock (this._tokenLock)
        {
            if (this._cachedAccessToken is null || this._cachedAccessToken.Value.ExpiresOn <= DateTimeOffset.Now)
            {
                // This will also get the first or refresh the token which is the responsibility of the underlying TokenCredential.GetToken implementation
                this._cachedAccessToken = this._tokenCredential.GetToken(new TokenRequestContext(this._scopes), CancellationToken.None);
            }
        }

        requestMessage.Headers.Authorization = new AuthenticationHeaderValue(
            "bearer",
            this._cachedAccessToken.Value.Token
        );
    }
}
