using Anthropic = Anthropic;
using CodeAnalysis = System.Diagnostics.CodeAnalysis;
using Generic = System.Collections.Generic;
using Json = System.Text.Json;
using Serialization = System.Text.Json.Serialization;
using System = System;

namespace Anthropic.Models.Messages;

[Serialization::JsonConverter(typeof(Anthropic::ModelConverter<Message>))]
public sealed record class Message : Anthropic::ModelBase, Anthropic::IFromRaw<Message>
{
    /// <summary>
    /// Unique object identifier.
    ///
    /// The format and length of IDs may change over time.
    /// </summary>
    public required string ID
    {
        get
        {
            if (!this.Properties.TryGetValue("id", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException("id", "Missing required argument");

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("id");
        }
        set { this.Properties["id"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Content generated by the model.
    ///
    /// This is an array of content blocks, each of which has a `type` that determines
    /// its shape.
    ///
    /// Example:
    ///
    /// ```json [{"type": "text", "text": "Hi, I'm Claude."}] ```
    ///
    /// If the request input `messages` ended with an `assistant` turn, then the response
    /// `content` will continue directly from that last turn. You can use this to constrain
    /// the model's output.
    ///
    /// For example, if the input `messages` were: ```json [   {"role": "user", "content":
    /// "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"},   {"role": "assistant",
    /// "content": "The best answer is ("} ] ```
    ///
    /// Then the response `content` might be:
    ///
    /// ```json [{"type": "text", "text": "B)"}] ```
    /// </summary>
    public required Generic::List<ContentBlock> Content
    {
        get
        {
            if (!this.Properties.TryGetValue("content", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "content",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<Generic::List<ContentBlock>>(element)
                ?? throw new System::ArgumentNullException("content");
        }
        set { this.Properties["content"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The model that will complete your prompt.\n\nSee [models](https://docs.anthropic.com/en/docs/models-overview)
    /// for additional details and options.
    /// </summary>
    public required Model Model
    {
        get
        {
            if (!this.Properties.TryGetValue("model", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException("model", "Missing required argument");

            return Json::JsonSerializer.Deserialize<Model>(element)
                ?? throw new System::ArgumentNullException("model");
        }
        set { this.Properties["model"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Conversational role of the generated message.
    ///
    /// This will always be `"assistant"`.
    /// </summary>
    public Json::JsonElement Role
    {
        get
        {
            if (!this.Properties.TryGetValue("role", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException("role", "Missing required argument");

            return Json::JsonSerializer.Deserialize<Json::JsonElement>(element);
        }
        set { this.Properties["role"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The reason that we stopped.
    ///
    /// This may be one the following values: * `"end_turn"`: the model reached a natural
    /// stopping point * `"max_tokens"`: we exceeded the requested `max_tokens` or the
    /// model's maximum * `"stop_sequence"`: one of your provided custom `stop_sequences`
    /// was generated * `"tool_use"`: the model invoked one or more tools * `"pause_turn"`:
    /// we paused a long-running turn. You may provide the response back as-is in a
    /// subsequent request to let the model continue. * `"refusal"`: when streaming
    /// classifiers intervene to handle potential policy violations
    ///
    /// In non-streaming mode this value is always non-null. In streaming mode, it is
    /// null in the `message_start` event and non-null otherwise.
    /// </summary>
    public required StopReason? StopReason
    {
        get
        {
            if (!this.Properties.TryGetValue("stop_reason", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "stop_reason",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<StopReason?>(element);
        }
        set { this.Properties["stop_reason"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Which custom stop sequence was generated, if any.
    ///
    /// This value will be a non-null string if one of your custom stop sequences was generated.
    /// </summary>
    public required string? StopSequence
    {
        get
        {
            if (!this.Properties.TryGetValue("stop_sequence", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "stop_sequence",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<string?>(element);
        }
        set { this.Properties["stop_sequence"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Object type.
    ///
    /// For Messages, this is always `"message"`.
    /// </summary>
    public Json::JsonElement Type
    {
        get
        {
            if (!this.Properties.TryGetValue("type", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException("type", "Missing required argument");

            return Json::JsonSerializer.Deserialize<Json::JsonElement>(element);
        }
        set { this.Properties["type"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Billing and rate-limit usage.
    ///
    /// Anthropic's API bills and rate-limits by token counts, as tokens represent
    /// the underlying cost to our systems.
    ///
    /// Under the hood, the API transforms requests into a format suitable for the
    /// model. The model's output then goes through a parsing stage before becoming
    /// an API response. As a result, the token counts in `usage` will not match one-to-one
    /// with the exact visible content of an API request or response.
    ///
    /// For example, `output_tokens` will be non-zero, even for an empty string response
    /// from Claude.
    ///
    /// Total input tokens in a request is the summation of `input_tokens`, `cache_creation_input_tokens`,
    /// and `cache_read_input_tokens`.
    /// </summary>
    public required Usage Usage
    {
        get
        {
            if (!this.Properties.TryGetValue("usage", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException("usage", "Missing required argument");

            return Json::JsonSerializer.Deserialize<Usage>(element)
                ?? throw new System::ArgumentNullException("usage");
        }
        set { this.Properties["usage"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    public override void Validate()
    {
        _ = this.ID;
        foreach (var item in this.Content)
        {
            item.Validate();
        }
        this.Model.Validate();
        if (!this.Role.Equals(Json::JsonSerializer.Deserialize<Json::JsonElement>("\"assistant\"")))
        {
            throw new System::Exception();
        }
        this.StopReason?.Validate();
        _ = this.StopSequence;
        if (!this.Type.Equals(Json::JsonSerializer.Deserialize<Json::JsonElement>("\"message\"")))
        {
            throw new System::Exception();
        }
        this.Usage.Validate();
    }

    public Message()
    {
        this.Role = Json::JsonSerializer.Deserialize<Json::JsonElement>("\"assistant\"");
        this.Type = Json::JsonSerializer.Deserialize<Json::JsonElement>("\"message\"");
    }

#pragma warning disable CS8618
    [CodeAnalysis::SetsRequiredMembers]
    Message(Generic::Dictionary<string, Json::JsonElement> properties)
    {
        Properties = properties;
    }
#pragma warning restore CS8618

    public static Message FromRawUnchecked(
        Generic::Dictionary<string, Json::JsonElement> properties
    )
    {
        return new(properties);
    }
}
